#!/usr/bin/env python3
"""Generate the tiny redistributable ONNX classifier and synthetic replay dataset."""

import hashlib
import json
from pathlib import Path

import numpy as np
import onnx
from onnx import TensorProto, helper, numpy_helper
from PIL import Image


ROOT = Path("crates/vision/tests/fixtures/classifier")


def main() -> None:
    ROOT.mkdir(parents=True, exist_ok=True)
    for pattern in ("*.png", "*.onnx"):
        for path in ROOT.glob(pattern):
            path.unlink()
    yy, xx = np.mgrid[:8, :8]
    distance = (xx - 3.5) ** 2 + (yy - 3.5) ** 2
    orb = ((distance >= 5.0) & (distance <= 11.0)).astype(np.float32)
    cross = ((abs(xx - yy) <= 0.5) | (abs(xx + yy - 7) <= 0.5)).astype(np.float32)
    prototypes = np.stack(
        [
            np.mean([np.roll(orb, shift=(dy, dx), axis=(0, 1)) for dy in (0, 1) for dx in (0, 1)], axis=0),
            np.mean([np.roll(cross, shift=(dy, dx), axis=(0, 1)) for dy in (0, 1) for dx in (0, 1)], axis=0),
        ]
    ).reshape(2, 64)
    # Negative squared-distance logits with the input-only x² term removed.
    weights = (2.0 * prototypes.T / 64.0).astype(np.float32)
    bias = (-(prototypes**2).sum(axis=1) / 64.0).astype(np.float32)
    graph = helper.make_graph(
        [
            helper.make_node("Flatten", ["input"], ["flat"], axis=1),
            helper.make_node("Gemm", ["flat", "weights", "bias"], ["logits"]),
        ],
        "synthetic_hud_icon_classifier",
        [helper.make_tensor_value_info("input", TensorProto.FLOAT, [1, 1, 8, 8])],
        [helper.make_tensor_value_info("logits", TensorProto.FLOAT, [1, 2])],
        [numpy_helper.from_array(weights, "weights"), numpy_helper.from_array(bias, "bias")],
    )
    model = helper.make_model(
        graph,
        producer_name="yash-app-events-fixture-generator",
        opset_imports=[helper.make_opsetid("", 13)],
    )
    model.ir_version = 8
    onnx.checker.check_model(model)
    model_path = ROOT / "hud_icon.onnx"
    onnx.save(model, model_path)

    rng = np.random.default_rng(7)
    cases = []
    for label, prototype in (("orb", orb), ("cross", cross)):
        for index in range(4):
            shifted = np.roll(prototype, shift=((index % 2), ((index // 2) % 2)), axis=(0, 1))
            pixels = np.clip(
                shifted * 210 + 20 + rng.integers(-10 - index, 11 + index, size=(8, 8)),
                0,
                255,
            ).astype(np.uint8)
            name = f"{label}_{index}.png"
            Image.fromarray(pixels, mode="L").save(ROOT / name)
            cases.append({"image": name, "expected": label})
    model_bytes = model_path.read_bytes()
    manifest = {
        "schema": 1,
        "model": model_path.name,
        "model_sha256": hashlib.sha256(model_bytes).hexdigest(),
        "input": {"width": 8, "height": 8, "channels": 1},
        "labels": ["orb", "cross"],
        "cases": cases,
        "license": "Generated by this repository; MIT OR Apache-2.0",
    }
    (ROOT / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")


if __name__ == "__main__":
    main()
